// @ts-nocheck

const formatUGX = (amount: number) =>
  `UGX ${new Intl.NumberFormat("en-US").format(Math.round(amount))}`;

export const exportEarningsStatement = async (
  rows: any[],
  employee: any,
  fullName: string,
) => {
  const pdfMake: any = await import("pdfmake/build/pdfmake.js");
  const pdfFonts: any = await import("pdfmake/build/vfs_fonts.js");
  pdfMake.vfs = pdfFonts.default.vfs;

  const docDefinition = {
    pageOrientation: "landscape" as const,
    pageMargins: [30, 30, 30, 30] as [number, number, number, number],
    content: [
      {
        columns: [
          {
            text: "ALHEB SCHOOL BLOOM",
            style: "headerLeft",
            width: "*",
          },
          {
            text: "EARNINGS STATEMENT",
            style: "headerRight",
            width: "auto",
          },
        ],
      },
      {
        canvas: [
          { type: "line", x1: 0, y1: 0, x2: 515, y2: 0, lineWidth: 2, lineColor: "#1e293b" },
        ],
        margin: [0, 2, 0, 10],
      },
      {
        columns: [
          {
            width: "*",
            stack: [
              { text: `Employee: ${fullName}`, style: "infoText" },
              { text: `TIN: ${employee?.tin_number || "N/A"}`, style: "infoText" },
              { text: `NSSF: ${employee?.nssf_number || "N/A"}`, style: "infoText" },
            ],
          },
          {
            width: "auto",
            stack: [
              { text: `Period: ${rows[0]?.month || "N/A"} - ${rows[rows.length - 1]?.month || "N/A"}`, style: "infoText", alignment: "right" },
              { text: `Generated: ${new Date().toLocaleDateString("en-UG")}`, style: "infoText", alignment: "right" },
            ],
          },
        ],
        margin: [0, 0, 0, 15],
      },
      {
        style: "earningsTable",
        table: {
          headerRows: 1,
          widths: ["auto", "*", "auto", "auto", "auto", "auto"],
          body: [
            [
              { text: "#", style: "tableHeader" },
              { text: "Period", style: "tableHeader" },
              { text: "Gross (UGX)", style: "tableHeader", alignment: "right" },
              { text: "Deductions (UGX)", style: "tableHeader", alignment: "right" },
              { text: "Bonuses (UGX)", style: "tableHeader", alignment: "right" },
              { text: "Net Pay (UGX)", style: "tableHeader", alignment: "right" },
            ],
            ...rows.map((r, i) => [
              { text: String(i + 1), style: "cellSmall", alignment: "center" },
              { text: r.month, style: "cellPeriod" },
              { text: (r.base_salary || 0).toLocaleString(), style: "cellNumber" },
              { text: (r.deductions || 0).toLocaleString(), style: "cellNumberRed" },
              { text: (r.bonuses || 0).toLocaleString(), style: "cellNumberGreen" },
              { text: (r.net_pay || 0).toLocaleString(), style: "cellNumberBold" },
            ]),
            [
              { text: "", colSpan: 1 },
              {},
              { text: rows.reduce((s, r) => s + Number(r.base_salary || 0), 0).toLocaleString(), style: "totalCell", alignment: "right" },
              { text: rows.reduce((s, r) => s + Number(r.deductions || 0), 0).toLocaleString(), style: "totalCellRed", alignment: "right" },
              { text: rows.reduce((s, r) => s + Number(r.bonuses || 0), 0).toLocaleString(), style: "totalCellGreen", alignment: "right" },
              { text: rows.reduce((s, r) => s + Number(r.net_pay || 0), 0).toLocaleString(), style: "totalCellBold", alignment: "right" },
            ],
          ],
        },
        layout: {
          hLineWidth: (i: number, node: any) => (i === 0 || i === node.table.body.length - 1 || i === 1 ? 1 : 0.3),
          vLineWidth: () => 0.3,
          hLineColor: () => "#cbd5e1",
          vLineColor: () => "#cbd5e1",
          paddingTop: (i: number) => (i === 0 ? 8 : 5),
          paddingBottom: (i: number) => (i === 0 ? 8 : 5),
          paddingLeft: () => 8,
          paddingRight: () => 8,
        },
      },
      {
        text: `Total Net YTD: ${formatUGX(rows.reduce((s, r) => s + Number(r.net_pay || 0), 0))}`,
        style: "summaryLine",
        margin: [0, 15, 0, 0],
      },
      {
        text: `\n\n_________________________\nAuthorized Signature`,
        style: "signature",
        alignment: "right",
        margin: [0, 20, 0, 0],
      },
      {
        text: `\nGenerated by Alheb School Bloom Management Suite`,
        style: "footer",
        alignment: "center",
        margin: [0, 20, 0, 0],
      },
    ],
    styles: {
      headerLeft: {
        fontSize: 16,
        bold: true,
        color: "#1e293b",
      },
      headerRight: {
        fontSize: 12,
        bold: true,
        color: "#64748b",
        alignment: "right",
      },
      infoText: {
        fontSize: 9,
        color: "#475569",
        margin: [0, 1, 0, 1],
      },
      tableHeader: {
        fontSize: 8,
        bold: true,
        color: "#ffffff",
        fillColor: "#1e293b",
        alignment: "center",
      },
      cellSmall: {
        fontSize: 9,
        color: "#64748b",
      },
      cellPeriod: {
        fontSize: 9,
        bold: true,
        color: "#1e293b",
      },
      cellNumber: {
        fontSize: 9,
        color: "#334155",
        alignment: "right",
      },
      cellNumberRed: {
        fontSize: 9,
        color: "#dc2626",
        alignment: "right",
      },
      cellNumberGreen: {
        fontSize: 9,
        color: "#16a34a",
        alignment: "right",
      },
      cellNumberBold: {
        fontSize: 9,
        bold: true,
        color: "#1e293b",
        alignment: "right",
      },
      totalCell: {
        fontSize: 9,
        bold: true,
        color: "#1e293b",
        fillColor: "#f1f5f9",
      },
      totalCellRed: {
        fontSize: 9,
        bold: true,
        color: "#dc2626",
        fillColor: "#f1f5f9",
      },
      totalCellGreen: {
        fontSize: 9,
        bold: true,
        color: "#16a34a",
        fillColor: "#f1f5f9",
      },
      totalCellBold: {
        fontSize: 10,
        bold: true,
        color: "#1e293b",
        fillColor: "#e2e8f0",
      },
      summaryLine: {
        fontSize: 11,
        bold: true,
        color: "#1e293b",
      },
      signature: {
        fontSize: 9,
        color: "#64748b",
      },
      footer: {
        fontSize: 7,
        color: "#94a3b8",
      },
    },
    defaultStyle: {
      fontFamily: "Roboto",
    },
  };

  pdfMake.createPdf(docDefinition).download("Earnings_Statement.pdf");
};

export const exportPayslip = async (row: any, employee: any, fullName: string) => {
  const pdfMake: any = await import("pdfmake/build/pdfmake.js");
  const pdfFonts: any = await import("pdfmake/build/vfs_fonts.js");
  pdfMake.vfs = pdfFonts.default.vfs;

  const gross = Number(row.base_salary || 0);
  const deductions = Number(row.deductions || 0);
  const bonuses = Number(row.bonuses || 0);
  const netPay = Number(row.net_pay || 0);

  const docDefinition = {
    pageSize: "A4" as const,
    pageMargins: [25, 25, 25, 25] as [number, number, number, number],
    content: [
      {
        columns: [
          {
            width: "*",
            stack: [
              { text: "ALHEB SCHOOL BLOOM", style: "psHeader" },
              { text: "OFFICIAL PAYSLIP", style: "psSubHeader" },
            ],
          },
          {
            width: "auto",
            stack: [
              { text: row.month, style: "psPeriod", alignment: "right" },
              { text: `Issued: ${new Date().toLocaleDateString("en-UG")}`, style: "psSmall", alignment: "right" },
            ],
          },
        ],
      },
      { canvas: [{ type: "line", x1: 0, y1: 0, x2: 515, y2: 0, lineWidth: 2, lineColor: "#1e293b" }], margin: [0, 2, 0, 10] },
      {
        columns: [
          {
            width: "*",
            stack: [
              { text: `Employee: ${fullName}`, style: "psInfo" },
              { text: `TIN: ${employee?.tin_number || "N/A"}`, style: "psInfo" },
              { text: `NSSF: ${employee?.nssf_number || "N/A"}`, style: "psInfo" },
            ],
          },
        ],
        margin: [0, 0, 0, 15],
      },
      {
        table: {
          headerRows: 1,
          widths: ["*", "auto"],
          body: [
            [
              { text: "Description", style: "psTableHeader" },
              { text: "Amount (UGX)", style: "psTableHeader", alignment: "right" },
            ],
            [
              { text: "Basic Salary", style: "psCell" },
              { text: gross.toLocaleString(), style: "psCellRight" },
            ],
            [
              { text: "Bonuses / Allowances", style: "psCellGreen" },
              { text: `+${bonuses.toLocaleString()}`, style: "psCellRightGreen" },
            ],
            [
              { text: "Deductions (PAYE, NSSF, etc.)", style: "psCellRed" },
              { text: `-${deductions.toLocaleString()}`, style: "psCellRightRed" },
            ],
            [
              { text: "NET PAY", style: "psTotalLabel" },
              { text: netPay.toLocaleString(), style: "psTotalAmount" },
            ],
          ],
        },
        layout: {
          hLineWidth: (i: number, node: any) => (i === 0 || i === node.table.body.length - 1 ? 1 : 0.3),
          vLineWidth: () => 0.3,
          hLineColor: () => "#cbd5e1",
          vLineColor: () => "#cbd5e1",
          paddingTop: () => 8,
          paddingBottom: () => 8,
          paddingLeft: () => 10,
          paddingRight: () => 10,
        },
      },
      {
        text: `\nPayment Method: Bank Transfer\nStatus: Paid`,
        style: "psSmall",
        margin: [0, 10, 0, 0],
      },
      {
        text: `\n\n_________________________\nAuthorized Signature`,
        style: "psSignature",
        alignment: "right",
        margin: [0, 20, 0, 0],
      },
      { text: `\nGenerated by Alheb School Bloom Management Suite`, style: "psFooter", alignment: "center" },
    ],
    styles: {
      psHeader: { fontSize: 14, bold: true, color: "#1e293b" },
      psSubHeader: { fontSize: 10, bold: true, color: "#64748b", margin: [0, 2, 0, 0] },
      psPeriod: { fontSize: 10, bold: true, color: "#334155" },
      psSmall: { fontSize: 8, color: "#64748b" },
      psInfo: { fontSize: 9, color: "#475569", margin: [0, 1, 0, 1] },
      psTableHeader: { fontSize: 9, bold: true, color: "#ffffff", fillColor: "#1e293b" },
      psCell: { fontSize: 9, color: "#334155" },
      psCellRight: { fontSize: 9, color: "#334155", alignment: "right" },
      psCellGreen: { fontSize: 9, color: "#16a34a" },
      psCellRightGreen: { fontSize: 9, color: "#16a34a", alignment: "right" },
      psCellRed: { fontSize: 9, color: "#dc2626" },
      psCellRightRed: { fontSize: 9, color: "#dc2626", alignment: "right" },
      psTotalLabel: { fontSize: 10, bold: true, color: "#1e293b", fillColor: "#f1f5f9" },
      psTotalAmount: { fontSize: 12, bold: true, color: "#1e293b", fillColor: "#f1f5f9", alignment: "right" },
      psSignature: { fontSize: 9, color: "#64748b" },
      psFooter: { fontSize: 7, color: "#94a3b8" },
    },
    defaultStyle: { fontFamily: "Roboto" },
  };

  pdfMake.createPdf(docDefinition).download(`Payslip_${row.month.replace(/\s+/g, "_")}.pdf`);
};
