import { 
  LayoutDashboard, 
  Users, 
  GraduationCap, 
  BookOpen, 
  Calendar, 
  ClipboardCheck, 
  Bell, 
  Shield, 
  Box, 
  Stethoscope, 
  Bed, 
  Scale, 
  Wallet, 
  ShoppingCart, 
  Receipt, 
  UserCheck, 
  BarChart3, 
  HardHat, 
  Layers, 
  Mic,
  UserCog, 
  CreditCard, 
  Clock, 
  FileText, 
  FileCheck,
  FileUp,
  PenLine, 
  BookMarked, 
  Star,
  Settings2,
  Pill,
  Package,
  Heart,
  Fingerprint,
  Building,
  ClipboardList,
  Wind,
  Utensils,
  Plane,
  Scissors,
} from "lucide-react";
import { AppRole } from "@/hooks/useAuth";

export interface NavItem {
  icon: any;
  labelKey: string;
  path: string;
  roles?: AppRole[];
  adminOnly?: boolean;
}

export interface NavSection {
  titleKey: string;
  items: NavItem[];
}

export const navSections: NavSection[] = [
  {
    titleKey: "Executive & Governance",
    items: [
      { icon: Shield, labelKey: "Director Dashboard", path: "/director", roles: ["admin", "center_director"] },
      { icon: UserCog, labelKey: "Director Users", path: "/director/users", roles: ["admin", "center_director"] },
      { icon: BarChart3, labelKey: "Executive Reports", path: "/director/reports", roles: ["admin", "center_director"] },
      { icon: FileCheck, labelKey: "Approval Workflow", path: "/director/approvals", roles: ["admin", "center_director"] },
      { icon: LayoutDashboard, labelKey: "Headteacher Hub", path: "/headteacher", roles: ["admin", "head_teacher"] },
      { icon: LayoutDashboard, labelKey: "Manager Command", path: "/manager", roles: ["admin", "direct_manager"] },
      { icon: FileCheck, labelKey: "Manager Approvals", path: "/manager/approvals", roles: ["admin", "direct_manager"] },
      { icon: Star, labelKey: "Staff Performance", path: "/manager/performance", roles: ["admin", "direct_manager"] },
      { icon: Users, labelKey: "Governance Board", path: "/governance", roles: ["admin", "head_teacher", "center_director", "direct_manager"] },
      { icon: FileText, labelKey: "Ministry & Compliance", path: "/ministry", roles: ["admin", "head_teacher", "center_director", "direct_manager"] },
    ],
  },
  {
    titleKey: "Academic Control",
    items: [
      { icon: GraduationCap, labelKey: "DOS Command Center", path: "/dos", roles: ["admin", "head_teacher", "dos"] },
      { icon: Star, labelKey: "Theology DOS Hub", path: "/theology", roles: ["admin", "dos_theology"] },
      { icon: GraduationCap, labelKey: "IPLE Management", path: "/dos/iple", roles: ["admin", "head_teacher", "dos_theology"] },
      { icon: BookMarked, labelKey: "Subjects", path: "/dos/subjects", roles: ["admin", "head_teacher", "dos"] },
      { icon: Users, labelKey: "Learner Management", path: "/students", roles: ["admin", "teacher", "head_teacher", "dos", "accountant", "staff", "orphan_supervisor", "theology_teacher", "head_of_internal"] },
      { icon: GraduationCap, labelKey: "Staff & Teacher Hub", path: "/teachers", roles: ["admin", "head_teacher", "dos", "head_of_internal"] },
      { icon: BookOpen, labelKey: "Academic Classes", path: "/classes", roles: ["admin", "teacher", "head_teacher", "dos", "head_of_internal"] },
      { icon: Star, labelKey: "Madrasa & Islamic", path: "/madrasa", roles: ["admin", "teacher", "head_teacher", "islamic_coordinator", "sheikh", "imam", "orphan_supervisor", "dos_theology", "theology_teacher"] },
      { icon: BookMarked, labelKey: "Digital Homework", path: "/homework", roles: ["admin", "teacher", "head_teacher", "dos"] },
      { icon: PenLine, labelKey: "Enter Marks", path: "/marks", roles: ["admin", "teacher", "head_teacher", "dos", "dos_theology", "theology_teacher", "head_of_internal"] },
      { icon: Calendar, labelKey: "School Timetables", path: "/dos/timetable", roles: ["admin", "head_teacher", "dos"] },
      { icon: BookMarked, labelKey: "Curriculum Coverage", path: "/dos/syllabus", roles: ["admin", "head_teacher", "dos"] },
      { icon: PenLine, labelKey: "Exams & Grading", path: "/dos/exams", roles: ["admin", "head_teacher", "dos"] },
      { icon: FileText, labelKey: "Marks & Reports", path: "/reports", roles: ["admin", "head_teacher", "teacher", "dos"] },
      { icon: ClipboardCheck, labelKey: "Learner Attendance", path: "/attendance", roles: ["admin", "teacher", "head_teacher", "dos", "orphan_supervisor", "head_of_internal"] },
      { icon: FileText, labelKey: "P7 Management", path: "/dos/p7-management", roles: ["admin", "head_teacher", "dos"] },
      { icon: Clock, labelKey: "Lesson Tracking", path: "/dos/lesson-tracking", roles: ["admin", "head_teacher", "dos"] },
      { icon: BookMarked, labelKey: "Curriculum Setup", path: "/dos/curriculum-setup", roles: ["admin", "head_teacher", "dos"] },
      { icon: PenLine, labelKey: "Scheme of Work", path: "/dos/scheme-of-work", roles: ["admin", "head_teacher", "teacher", "dos"] },
      { icon: BarChart3, labelKey: "Syllabus Coverage", path: "/dos/syllabus-coverage", roles: ["admin", "head_teacher", "dos"] },
      { icon: FileText, labelKey: "Syllabus Reports", path: "/dos/syllabus-reports", roles: ["admin", "head_teacher", "dos"] },
      { icon: Bed, labelKey: "Hostel Oversight", path: "/dos/hostel", roles: ["admin", "head_teacher", "dos"] },
    ],
  },
  {
    titleKey: "Theology & IPLE",
    items: [
      { icon: Star, labelKey: "My Theology Dashboard", path: "/teacher/theology", roles: ["admin", "theology_teacher"] },
      { icon: PenLine, labelKey: "Islamic Marks Entry", path: "/marks?tab=islamic", roles: ["admin", "theology_teacher", "dos_theology"] },
      { icon: BookOpen, labelKey: "Madrasa & Quran", path: "/madrasa", roles: ["admin", "theology_teacher", "dos_theology"] },
      { icon: GraduationCap, labelKey: "IPLE Management", path: "/dos/iple", roles: ["admin", "dos_theology", "theology_teacher"] },
      { icon: Mic, labelKey: "Oral Assessments", path: "/dos/iple?tab=oral", roles: ["admin", "dos_theology", "theology_teacher"] },
      { icon: Users, labelKey: "Islamic Learners", path: "/students?track=islamic", roles: ["admin", "theology_teacher", "dos_theology"] },
      { icon: Clock, labelKey: "Lesson Register", path: "/teacher/lesson-register", roles: ["admin", "teacher", "theology_teacher"] },
      { icon: BookMarked, labelKey: "Lesson Planner", path: "/teacher/lesson-planner", roles: ["admin", "teacher", "theology_teacher"] },
      { icon: Calendar, labelKey: "School Timetables", path: "/dos/timetable", roles: ["admin", "head_teacher", "dos", "theology_teacher"] },
    ],
  },
  {
    titleKey: "Finance & Accounts",
    items: [
      { icon: Wallet, labelKey: "Finance Overview", path: "/accountant", roles: ["admin", "accountant", "head_teacher"] },
      { icon: Wallet, labelKey: "Financial Accounts", path: "/accountant/accounts", roles: ["admin", "accountant"] },
      { icon: Receipt, labelKey: "Fees & Collections", path: "/accountant/fees", roles: ["admin", "accountant", "head_teacher"] },
      { icon: ShoppingCart, labelKey: "Procurement & Store", path: "/accountant/procurement", roles: ["admin", "accountant"] },
      { icon: CreditCard, labelKey: "Payroll & Salaries", path: "/salary", roles: ["admin", "accountant", "head_teacher"] },
      { icon: UserCheck, labelKey: "HR & Payroll", path: "/accountant/payroll", roles: ["admin", "accountant"] },
      { icon: BarChart3, labelKey: "Budget Planning", path: "/budget", roles: ["admin", "accountant", "head_teacher"] },
      { icon: Receipt, labelKey: "Petty Cash Management", path: "/accountant/petty-cash", roles: ["admin", "accountant"] },
      { icon: Receipt, labelKey: "Fees Tracking", path: "/accountant/fees-tracking", roles: ["admin", "accountant"] },
      { icon: Scale, labelKey: "Reconciliation", path: "/accountant/reconciliation", roles: ["admin", "accountant"] },
      { icon: FileCheck, labelKey: "Expense Approvals", path: "/accountant/expense-approvals", roles: ["admin", "accountant"] },
      { icon: FileText, labelKey: "Tax Reports", path: "/accountant/tax-reports", roles: ["admin", "accountant"] },
      { icon: ClipboardCheck, labelKey: "Finance Audit Log", path: "/accountant/audit-log", roles: ["admin", "accountant"] },
    ],
  },
  {
    titleKey: "Campus Operations",
    items: [
      { icon: Box, labelKey: "Store & Inventory Hub", path: "/store", roles: ["admin", "staff", "head_teacher"] },
      { icon: Box, labelKey: "Resource Inventory", path: "/inventory", roles: ["admin", "staff", "head_teacher"] },
      { icon: Box, labelKey: "Receiving & Internal", path: "/store/receiving", roles: ["admin", "staff"] },
      { icon: BarChart3, labelKey: "Stock Alerts", path: "/store/low-stock", roles: ["admin", "staff", "accountant"] },
      { icon: Users, labelKey: "Supplier Database", path: "/store/suppliers", roles: ["admin", "staff", "accountant"] },
      { icon: Shield, labelKey: "Gate Control Hub", path: "/gate", roles: ["admin", "security", "gateman"] },
      { icon: Clock, labelKey: "Vehicle Log", path: "/gate/vehicles", roles: ["admin", "security", "gateman"] },
      { icon: FileText, labelKey: "Exit Passes", path: "/gate/exit-passes", roles: ["admin", "security", "gateman"] },
      { icon: Users, labelKey: "Gate Handover", path: "/gate/handover", roles: ["admin", "security", "gateman"] },
      { icon: FileText, labelKey: "Office Management", path: "/office", roles: ["admin", "head_teacher", "staff", "secretary", "office_manager"] },
      { icon: FileText, labelKey: "Official Documents", path: "/office/documents", roles: ["admin", "head_teacher", "staff", "secretary", "office_manager"] },
      { icon: FileUp, labelKey: "Print Orders", path: "/office/print-orders", roles: ["admin", "secretary", "office_manager", "teacher", "staff"] },
      { icon: Box, labelKey: "Delivery Log", path: "/secretary/deliveries", roles: ["admin", "secretary", "office_manager", "staff"] },
      { icon: Bell, labelKey: "Comms & Circulars", path: "/office/comms", roles: ["admin", "head_teacher", "staff", "secretary", "office_manager"] },
      { icon: Stethoscope, labelKey: "Medical Infirmary Hub", path: "/nurse", roles: ["admin", "head_teacher", "staff", "nurse"] },
      { icon: Pill, labelKey: "Prescriptions", path: "/nurse/prescriptions", roles: ["admin", "nurse", "head_teacher"] },
      { icon: Package, labelKey: "Pharmacy Inventory", path: "/nurse/pharmacy-inventory", roles: ["admin", "nurse", "head_teacher"] },
      { icon: BarChart3, labelKey: "Pharmacy Reports", path: "/nurse/pharmacy-reports", roles: ["admin", "nurse", "head_teacher"] },
      { icon: Stethoscope, labelKey: "Health Records", path: "/health", roles: ["admin", "head_teacher", "staff", "nurse", "orphan_supervisor"] },
      { icon: Bed, labelKey: "Residential Hostels", path: "/hostel", roles: ["admin", "staff", "head_teacher", "matron", "center_director", "director", "orphan_supervisor"] },
      { icon: Heart, labelKey: "Orphanage Services", path: "/orphanage", roles: ["admin", "head_teacher", "director", "orphan_supervisor"] },
      { icon: Scale, labelKey: "Discipline & Conduct", path: "/discipline", roles: ["admin", "head_teacher"] },
      { icon: BookOpen, labelKey: "Library", path: "/library", roles: ["admin", "teacher", "staff", "head_teacher", "accountant"] },
      { icon: ClipboardList, labelKey: "Kitchen Operations", path: "/kitchen", roles: ["admin", "cook", "storekeeper", "head_teacher"] },
      { icon: ShoppingCart, labelKey: "Store Orders", path: "/kitchen/store-orders", roles: ["admin", "cook", "storekeeper", "head_teacher"] },
      { icon: Package, labelKey: "Food Inventory", path: "/kitchen/inventory", roles: ["admin", "cook", "storekeeper", "head_teacher"] },
      { icon: Utensils, labelKey: "Meal Log", path: "/kitchen/meals", roles: ["admin", "cook", "head_teacher"] },
      { icon: Calendar, labelKey: "Weekly Menu", path: "/kitchen/menu", roles: ["admin", "cook", "head_teacher"] },
      { icon: Scissors, labelKey: "Tailor Workshop", path: "/tailor", roles: ["admin", "tailor", "head_teacher", "center_director"] },
    ],
  },
  {
    titleKey: "Residential Life",
    items: [
      { icon: LayoutDashboard, labelKey: "Matron Dashboard", path: "/matron", roles: ["admin", "matron", "head_teacher"] },
      { icon: Building, labelKey: "Dormitories", path: "/matron/dormitories", roles: ["admin", "matron", "head_teacher"] },
      { icon: Users, labelKey: "Residents", path: "/matron/residents", roles: ["admin", "matron", "head_teacher"] },
      { icon: ClipboardList, labelKey: "Essentials", path: "/matron/essentials", roles: ["admin", "matron", "head_teacher"] },
      { icon: Package, labelKey: "Supplies", path: "/matron/supplies", roles: ["admin", "matron", "head_teacher"] },
      { icon: Wind, labelKey: "Washing & Laundry", path: "/matron/washing", roles: ["admin", "matron", "head_teacher"] },
      { icon: Plane, labelKey: "Holiday Arrivals", path: "/matron/arrivals", roles: ["admin", "matron", "head_teacher"] },
    ],
  },
  {
    titleKey: "Systems & HR",
    items: [
        { icon: HardHat, labelKey: "HR Management", path: "/staff", roles: ["admin", "head_teacher", "staff", "head_of_internal"] },
        { icon: ClipboardCheck, labelKey: "Staff Daily Attendance", path: "/staff-attendance", roles: ["admin", "head_teacher", "head_of_internal"] },
        { icon: Layers, labelKey: "Staff Assignments", path: "/staff-assignments", roles: ["admin"], adminOnly: true },
        { icon: Box, labelKey: "Asset & Item Tracking", path: "/inventory/tracking", roles: ["admin", "staff", "head_of_internal"] },
        { icon: CreditCard, labelKey: "ID Card System", path: "/id-cards", roles: ["admin", "head_teacher", "staff"] },
        { icon: UserCog, labelKey: "Access Control", path: "/director/users", roles: ["admin", "head_teacher"] },
        { icon: Shield, labelKey: "Compliance Portal", path: "/ministry", roles: ["admin", "head_teacher"] },
    ],
  },
  {
    titleKey: "Internal Affairs",
    items: [
      { icon: LayoutDashboard, labelKey: "Internal Dashboard", path: "/internal", roles: ["admin", "head_of_internal"] },
      { icon: Scale, labelKey: "Discipline & Conduct", path: "/discipline", roles: ["admin", "head_teacher", "head_of_internal"] },
      { icon: FileText, labelKey: "Office Management", path: "/office", roles: ["admin", "head_teacher", "staff", "secretary", "office_manager", "head_of_internal"] },
      { icon: FileText, labelKey: "Official Documents", path: "/office/documents", roles: ["admin", "head_teacher", "staff", "secretary", "office_manager", "head_of_internal"] },
      { icon: FileText, labelKey: "Staff Letters", path: "/teacher/letters", roles: ["admin", "teacher", "staff", "head_of_internal"] },
      { icon: Bell, labelKey: "Comms & Circulars", path: "/office/comms", roles: ["admin", "head_teacher", "staff", "secretary", "office_manager", "head_of_internal"] },
    ],
  },
  {
    titleKey: "Personal Workspace",
    items: [
      { icon: LayoutDashboard, labelKey: "My Dashboard", path: "/", roles: ["admin", "staff", "teacher", "security", "gateman", "parent", "accountant", "head_teacher", "dos_theology", "theology_teacher", "head_of_internal"] },
      { icon: Bell, labelKey: "Staff Messaging", path: "/teacher/inbox", roles: ["admin", "teacher", "staff", "security", "gateman", "head_teacher", "deputy_head_teacher", "matron", "nurse", "cook", "storekeeper", "dos", "dos_theology", "theology_teacher", "head_of_internal", "accountant"] },
      { icon: GraduationCap, labelKey: "My Managed Classes", path: "/teacher/my-classes", roles: ["admin", "teacher"] },
      { icon: PenLine, labelKey: "Lesson Planner", path: "/teacher/lesson-planner", roles: ["admin", "teacher"] },
      { icon: Clock, labelKey: "Lesson Register", path: "/teacher/lesson-register", roles: ["admin", "teacher"] },
      { icon: BookOpen, labelKey: "Learner Gradebook", path: "/teacher/gradebook", roles: ["admin", "teacher"] },
      { icon: Users, labelKey: "Parent Communication", path: "/teacher/parent-chat", roles: ["admin", "teacher"] },
      { icon: FileText, labelKey: "Staff Letters", path: "/teacher/letters", roles: ["admin", "teacher", "staff", "head_of_internal", "dos", "head_teacher", "deputy_head_teacher"] },
      { icon: ClipboardCheck, labelKey: "My Attendance", path: "/teacher/my-attendance", roles: ["admin", "teacher", "staff", "head_of_internal", "dos", "head_teacher", "deputy_head_teacher", "accountant"] },
      { icon: FileCheck, labelKey: "My Leave Requests", path: "/teacher/requests", roles: ["admin", "teacher", "staff", "head_of_internal", "dos", "head_teacher", "deputy_head_teacher", "accountant"] },
      { icon: Clock, labelKey: "Class Schedule", path: "/schedule", roles: ["admin", "teacher", "head_teacher", "dos", "deputy_head_teacher"] },
      { icon: Calendar, labelKey: "Events Calendar", path: "/calendar", roles: ["admin", "teacher", "staff", "security", "gateman", "parent", "head_teacher", "accountant", "dos", "deputy_head_teacher"] },
      { icon: Wallet, labelKey: "Personal Finance", path: "/teacher/finance", roles: ["admin", "teacher", "staff", "security", "gateman", "head_teacher", "deputy_head_teacher", "matron", "nurse", "cook", "storekeeper", "dos", "dos_theology", "theology_teacher", "head_of_internal", "accountant"] },
    ],
  },
];

export const bottomNavItems: NavItem[] = [
  { icon: UserCog, labelKey: "Account Settings", path: "/account-settings" },
  { icon: Bell, labelKey: "Notifications", path: "/notifications", roles: ["admin"] },
  { icon: Settings2, labelKey: "System Settings", path: "/settings", roles: ["admin", "head_teacher"] },
  { icon: Fingerprint, labelKey: "Attendance Device", path: "/hikvision", roles: ["admin", "head_teacher", "director"] },
];
